import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:dropdown_search/dropdown_search.dart';

class FormSelectionScreen extends StatefulWidget {
  const FormSelectionScreen({Key? key}) : super(key: key);

  @override
  _FormSelectionScreenState createState() => _FormSelectionScreenState();
}

class _FormSelectionScreenState extends State<FormSelectionScreen> {
  final List<String> formNames = [
    "Others",
    "Laxmi Bai Social security pension scheme",
    "BIhar Diesel Grant Scheme",
    "Rashtriya Aarogya Nidhi",
    "PM Employment Generation Progrmme",
    "Bihar Patrakar samman yojana",
    "PM Matru Vandana Yojana",
    "PM Matsya Sampada Yojana",
    "Post Graduate Indira Gandhi Scholarship For Single Girl Child",
    "Junior Research Fellowship",
    "Pradhan Mantri Awaas Yojana Gramin",
    "Indira Gandhi National Widow Pension Scheme",
    "Integrated poultry development scheme",
    "Janani Baal Suraksha Yojana",
    "Mukhyamantri Balak / Balika Bicycle Scheme",
    "Bihar Student Credit Card Scheme",
    "Bihar Saur Kranti Sinchai Yojana",
    "Pradhan Mantri Ujjwala Yojana",
    "Mahila Samman Savings Certificate",
    "Alpasankhyak Kalyan Chhatravas",
    "Bihar Udyamai Yojana",
    "Mukhyamantri Anusuchit Jati Evam Anusuchit Janjati Civil Seva Protsahan Yojana",
    "Bihar Unemployment Allowance Scheme",
    "Mukhyamantri Kanya Utthaan Yojana",
    "Shauchalay Nirman Ghar ka Samman",
    "Mukhyamantri Prakhand Transport Scheme",
    "post-matric scholarship for BC-EBC",
    "Pradhan Mantri Jeevan Jyoti Yojana",
    "Atal Beemit Vyakti Kalyan Yojana (ABVKY)",
    "Pradhan Mantri Garib Kalyan Anna Yojana",
    "Stand-up India",
    "Education Loan Scheme",
    "Swachh Bharat Mission – Urban 2.0",
    "Niramaya Health Insurance Scheme",
    "Nikshay Poshan Yojana",
    "Pradhan Mantri Jan Dhan Yojana",
    "MANAGE Internship Programme",
    "Kisan Credit Card Scheme",
    "Mukhyamantri Harit Krishi Sanyantra Yojana",
    "Bihar Victim Compensation Scheme",
    "BSMEB Scholarships to Meritorious Fauquania & Molvi Madrasa Students",
    "Kushal Yuva Program",
    "Bihar Rajya Fasal Sahayata Yojana",
    "National Talent Scholarship (NTS) Undergraduate",
    "Mukhayamantri Alpasankheyak Rozgar Rin Yojana",
    "Post Matric Scholarship for Minorities",
    "Journalist Welfare Scheme",
    "Khadi Karigar Janashree Bima Yojana",
    "Incubation Scheme",
    "Mukhyamantri Balak/Balika Protsahan Yojna",
    "Arakshit Rozgar Mahila ka Adhikar",
    "Awsar Badhe, Aage Padhe",
    "Bihar Anganwadi Beneficiary Scheme",
    "Bihar Mukhyamantri Atyant Pichhda Varg Civil Seva Protsahan Yojana (EBC Students)",
    "Bihar Mukhyamantri Vridhajan Pension Yojana",
    "Ghar tak Pakki Gali-Naliyan",
    "Bihar Har Ghar Bijli Yojana",
    "Har Ghar Nal Ka Jal",
    "Krishi Input Subsidy Scheme",
    "Krishi Vaniki Yojana",
    "Rajya Samajik Suraksha Pension Yojana",
    "Thalassemia Bal Sewa Yojana",
    "Sukanya Samriddhi Scheme",
    "Scheme for critical care and support for accessing justice to POCSO victims",
    "PM Vishwakarma scheme",
    "Atal Pension Yojana",
    "SMILE Scheme",
    "Dr. Ambedkar interest subsidy on Educational Loan",
    "Honey Mission Programme / Beekeeping",
    "Ambedkar Social Innovation & Incubation Mission",
    "Pragati Scholarship Scheme For Girl Students (Technical Diploma)",
    "NBCFDC General Loan Scheme",
    "One Nation, One Ration Card",
    "Mahila Samridhi Yojana (MSY)",
    "GST Exemption Certificate Scheme",
    "Rashtriya Parivar Sahayata Yojana",
    "Kabir Puraskar Scheme",
    "New Swarnima Scheme For Women",
    "Skill Testing & Certification",
    "Jal Jeevan Mission",
    "Pravasi Bharatiya Bima Yojana",
    "Pradhan Mantri Uchchatar Shiksha Protsahan Yojana: Central Sector Interest Subsidy Scheme",
    "Pradhan Mantri Kaushal Vikas Yojana(PMKVY)",
    "Mukhyamantri Nischay Swayam Sahayata Bhatta Yojna",
    "Mahila Samriddhi Yojana",
    "Pashu Bima Yojna",
    "Kushal Yuva Programme",
    "Bihar Startup Policy",
    "Bihar Rajya Fasal Sahayata Yojana",
    "Surakshit Matritva Ashwasan Yojana",
    "Anugrah Anudan",
    "Right to Information Fellowship",
    "Kisan Vikas Patra (KVP)",
    "Youth Hostel Scheme",
    "Pandit Deendayal Upadhyay National Welfare Fund For Sportspersons",
    "Pradhan Mantri Rashtriya Bal Puraskar",
    "WISE(Women in Science and Engineering)-KIRAN Post Doctoral Fellowship",
    "DPIIT Internship Scheme",
    "DRDO Scholarship Scheme for Girls",
    "Rashtriya Bal Swasthya Karyakram",
    "PM’s Scheme for Mentoring Young Authors",
    "Internship Programme At Serious Fraud Investigation Office",
    "NITI Internship Scheme",
    "National Water Awards",
    "Pilgrimage Rejuvenation and Spiritual Augmentation Drive (PRASHAD)",
    "National Bamboo Mission",
    "Agri-Clinics And Agri-Business Centres Scheme",
    "Swatantrata Sainik Samman Pension Scheme",
    "Kabir Puraskar Scheme",
    "Pradhan Mantri Bhartiya Janaushadhi Pariyojana",
    "Tagore National Fellowship for Cultural Research",
    "Paramparagat Krishi Vikas Yojana",
    "Savitribai Jyotirao Phule Fellowship For Single Girl Child",
    "Rashtriya Krishi Vikas Yojana (RKVY)",
    "Agnipath Yojana",
    "Maulana Azad National Fellowship For Minority Students",
    "National Renewable Energy Internship (NREI) Scheme",
    "Tenzing Norgay National Adventure Award",
    "Good Samaritan Scheme",
    "National Awards for Outstanding Services in the field of Prevention of Alcoholism and Substance (Drug) Abuse",
    "Innovation In Science Pursuit For Inspired Research (INSPIRE) - Faculty Fellowship",
    "Mission Solar Charkha",
    "Jute Raw Material Bank Scheme (JRMB)",
    "SWADHAR Greh (A Scheme For Women In Difficult Circumstances)",
    "National Youth Award",
    "CBSE Merit Scholarship Scheme For Single Girl Child",
    "Rastriya Arogya Nidhi - Health Minister’s Cancer Patient Fund",
    "Assistance To Disabled Persons For Purchase/Fitting Of Aids/Appliances",
    "Green Business Scheme",
    "National Action Plan for Skill Development of Persons with Disabilities (NAP-SDP)",
    "Scheme For Award Of Financial Assistance For Education To The Wards Of Beedi/Cine/IOMC/LSDM Workers – Pre & Post-Matric",
    "Mukhyamantri Kanya Vivah Yojana",
    "Mukhyamantri SC/ ST Civil Seva Protsahan Yojana 2024",
    "Bihar udhyami Yojana",
    "Support for Value Addition - Support to R&G units",
    "Dr. D.S. Kothari Post Doctoral Fellowships in Sciences",
    "AICTE – Saksham Scholarship Scheme For Specially-Abled Student (Diploma)",
    "Women In Science and Engineering-Societal Challenges with Opportunities Fellowship",
    "National Award For Senior Citizens (vayoshreshtha Samman): Sports And Adventure",
    "Land Ports Authority Of India (LPAI) Internship Scheme",
    "Nariyal Paudha Vitaran Karykram",
    "Kela Vikas Yojana",
    "Papita Vikas Yojana",
    "Aam vukas Yojana",
    "Phal Vikas Yojana",
    "National AIDS Control Organisation (NACO) Internship Programme",
    "National Awards To Teachers (Higher Education)",
    "Internship Scheme Of Employees’ Provident Fund Organisation (EPFO)",
    "Makhana Vikas Yojana",
    "Prime Minister’s Scholarship Scheme for the Wards of Central Armed Police Forces & Assam Rifles",
    "Khule Phool Ki Kheti Yojana",
    "Jhopadi me Mushroom Utpadan Yojana",
    "Mushroom Kit Distribution Scheme",
    "Mushroom Utpadan / Compost / Spon Yojana",
    "Kharif pyaaz ka Kshetr Vistar yojana",
    "Makhana Bhandar Grih Yojana",
    "Pyaaj bhandaran Yojana",
    "Madhumakkhee paalan evan madhu utpaadan yojana (2024-25) Under Integrated Horticulture Development Mission",
    "madhumakkhee paalan evan madhu utpaadan kaaryakram (raajy yojana) 2024-25",
    "Bihar Cold Storage Subsidy Yojana 2024",
    "Biotechnology Ignition Grant Scheme",
    "Pradhan Mantri Jeevan Jyoti Bima Yojana",
    "Pradhan Mantri Kaushal Vikas Yojana - Short Term Training",
    "Prime Minister's Scholarship Scheme for Railway Protection Force",
    "Ministry Of Social Justice and Empowerment",
    "Ramalingaswami Re-Entry Fellowship",
    "NSAP - Indira Gandhi National Old Age Pension Scheme",
    "ASEAN-India Research Training Fellowship (AI-RTF)",
    "JUNIOR RESEARCH FELLOWSHIP (JRF)",
    "AND RESEARCH ASSOCIATESHIP (RA) FOR FOREIGN NATIONALS",
    "Visvesvaraya PhD Scheme For Electronics & IT",
    "Pradhan Mantri Gram Sadak Yojana",
    "ICAR-Post Matric Scholarship For Scheduled Caste / Scheduled Tribes Candidates",
    "RMEWF-Financial Assistance For Ex-Servicemen In Penury",
    "Institutional Support for Development and Marketing of Tribal Products/Produce",
    "Mukhyamantri Prakhand Parivahan Yojana",
    "Mukhyamantri Divyangjan Sashaktikaran Chhatra Yojana",
    "Chief Minister Nari Shakti Yojana",
    "Lakshmi Bai Samajik Suraksha Pension Yojana",
    "Reimbursement of Membership fee of Government promoted e-commerce portals Scheme- NSSH",
    "phasal vividhikaran yojana (shushk baagavaanee 2024-25)",
    "raajy yojana antargat makhaana vikaas yojana (2024-25)",
    "chaay vikaas yojana (2024-25)",
    "klastar mein baagavaanee kee yojana (2024-25)",
    "Bihar Agri Investment Promotion Policy",
    "keet prabandhan hetu lait traip ke kray par anudaan hetu prapatr - raajy yojana",
    "keet-vyaadhi prabandhan hetu paudha sanrakshan upaadaan kray par anudaan hetu prapatr",
    "bageechon mein samekit kit prabandhan yojana",
    "Beej Anudan Yojana",
    "Mahila Kisan Sashaktikaran Pariyojana",
    "Haldhar Organic Farmer Award",
    "Visiting Advanced Joint Research Faculty Scheme",
    "Financial Assistance for Development of Buddhist/Tibetan Arts and Culture",
    "Top Class Education For Students With Disabilities",
    "Prime Minister's Employment Generation Programme (PMEGP)",
    "MeitY - Visvesvaraya PhD Scheme For Electronics & IT",
    "Innovation In Science Pursuit For Inspired Research (INSPIRE) - Internship",
    "Pradhan Mantri Matsya Sampada Yojana",
    "Swarnajayanti Fellowships Scheme",
    "Coir Vikas Yojana-Skill Upgradation and Mahila Coir Yojana",
    "Reimbursement of membership Fee in Government promoted E-Commerce Portals",
    "Pre-Matric Scholarships to the Children of Those Engaged in Occupations Involving Cleaning and Prone to Health Hazards",
    "Central Sector Scheme of National Fellowship for Providing Fellowship to Scheduled Caste Students to Pursue M.Phil. & PhD",
    "Indian Community Welfare Fund",
    "Saansad Adarsh Gram Yojana",
    "Indo-French Visiting/Mobility Programme for Women in Science",
    "Fellowship For Superannuated Faculty Members",
    "Jagjivan Ram Innovative Farmer Award",
    "N.G. Ranga Farmer Award for Diversified Agriculture",
    "Incentive Scheme for Acquisition of Plants and Machinery",
    "Jute Integrated Development Scheme",
    "Jute Raw Material Bank Scheme",
    "VAIshwik BHArtiya Vaigyanik (VAIBHAV) Fellowship",
    "National Mission on Natural Farming",
    "National Mission for Sustainable Agriculture",
    "AICTE-Margdarshan scheme",
    "National Award For Senior Citizens (Vayoshreshtha Samman): Best District Panchayat In Providing Services And Facilities To Senior Citizens",
    "HRIDAY: Heritage City Development & Augmentation Yojana",
    "Vocational Education and Training Loan Scheme",
    "National Mission on Edible Oils- Oil Palm",
    "Biotech-KISAN",
    "SERB International Research Experience(Science and Engineering Research Board)",
    "Group Workshed Scheme",
    "Central Vigilance Commission (CVC) Internship Scheme",
    "Samarth-Respite Care Scheme",
    "Startup India Seed Fund Scheme- For Incubators",
    "AICTE-Professional Development Scheme",
    "Internship Policy Of Indian Council For Cultural Relations (ICCR)",
    "National Post Doctoral Fellowship",
    "NPC Students Internship Program",
    "Internship Programme Of The Department Of Expenditure",
    "Star College Scheme For Strengthening Of Science Education And Training At Undergraduate Level",
    "SITARE-Gandhian Young Technological Innovation Award Grant",
    "BETI BACHAO BETI PADHAO SCHEME",
    "Scholarship Scheme for Girl Children of Jute Mills / MSMEs Workers",
    "Agri-Clinics And Agri-Business Centres Scheme",
    "Credit Based Schemes For SC - Aajeevika Micro-Finance Yojana (Livelihood Microfinance Scheme)",
    "BSR Scheme",
    "Interest Subsidy Eligibility Certificate (isec) Scheme",
    "National Awards For Empowerment Of Persons With Disabilities: Divyangjanon Ke Sashaktikaran Men Karyrat Sarveshrestha Sansthan (Private Organization, NGO)",
    "National Programme for Bovine Breeding and Dairy Development",
    "Scheme of Fund for Regeneration of Traditional Industries",
    "Coffee Development Programme in North Eastern Region: Quality Upgradation / Certification: Support for Eco-Certification / Organic Certification",
    "Development Support for Coffee in Traditional Areas: Eco-certification of Coffee",
    "Livestock Health and Diseases Control",
    "Tea Development and Promotion Scheme (TDPS): Plantation Development for Small Tea Growers (PDSTG): Mechanization for Individual Small Growers",
    "Agriculture And Processed Foods Export Promotion Scheme Of APEDA For The 15th Finance Commission Cycle (2021-22 To 2025-26)",
    "Krishonnati Yojana - Sub Mission On Seed And Planting Material (SMSP)",
    "Students Ready",
    "Kera Suraksha Insurance Scheme",
    "Internship Programme Of The Wildlife Crime Control Bureau (MoEFCC)",
    "RKVY Soil Health and Fertility - Soil Health Card",
    "Integrated Scheme for Export Promotion & Quality Improvement in Spices and Research and Development of Cardamom: Export Oriented Production: Large Cardamom Certified Nursery (Unit)",
    "Pradhan Mantri Krishi Sinchayee Yojana: Per Drop More Crop",
    "Coconut Palm Insurance Scheme",
    "ICRO Amrit Internship Programme",
    "SVAMITVA Yojana (Survey of Villages and Mapping with Improvised Technology in Village Areas)",
    "National Food Security Mission NFSM",
    "Mission on Integrated Development of Horticulture- NHM and HMNEH",
    "Development Support for Coffee in Traditional Areas: Water Augmentation",
    "Sub-mission On Agriculture Mechanization",
    "Agricultural Extension",
    "Agroforestry component under RKVY",
    "Cultural Function And Production Grant Scheme",
    "Pradhan Mantri Kisan Samman Nidhi",
    "National Scheme Of Welfare Of Fishermen",
    "Galvanizing Organic Bio-Agro Resources Dhan (GOBARdhan)",
    "Rainfed Area Development",
    "Integrated Scheme on Agriculture Cooperation",
    "National Agriculture Market",
    "Agriculture Infrastructure Fund",
    "Ramanujan Fellowship",
    "Agricultural Marketing Infrastructure",
    "National Scholarship For Post Graduate Studies",
    "Innovation In Science Pursuit For Inspired Research (INSPIRE) - Scholarship For Higher Education (SHE)",
    "Disha - Early Intervention and School Readiness Scheme",
    "National Handloom Development Programme (NHDP): Scholarship Component",
    "Long Term Fellowship under the Human Resource Development Programme for Health Research",
    "National Apprenticeship Promotion Scheme-2",
    "Capacity Building For Service Providers - Skill Testing & Certification",
    "Deendayal Antyodaya Yojana - National Rural Livelihoods Mission",
    "One Stop Centre",
    "Internship Programme for Women Students / Scholars / Social Activists / Teachers",
    "Rashtriya Gram Swaraj Abhiyan - Internship Program",
    "Rashtriya Gram Swaraj Abhiyan",
    "National Awards For Outstanding Services In The Field Of Prevention Of Alcoholism And Substance (Drug) Abuse: Best Integrated Rehabilitation Centre For Addicts (IRCA) For Providing Rehabilitation Services To Alcoholics And Drug Users",
    "Micro Credit Finance (NSFDC)",
    "National Overseas Scholarship For Students With Disabilities",
    "Scheme Of Assistance To Disabled Persons For Purchase/Fitting Of Aids/Appliances",
    "National Awards For Empowerment Of Persons With Disabilities: National Awards For Institutions Engaged In Empowering Persons With Disabilities: Sugamya Bharat Abhiyan Ke Karyanvayan/badhamukta Vatavaran Ke Srijan Mein Sarvshrestha Rajya/ Ut/ Zila",
    "Loan Based Schemes For Safai Karamchari - Sanitary Marts Scheme",
    "PM-YASASVI: Top Class School Education for OBC, EBC and DNT Students",
    "Indo-French Postdoctoral Research Programme for Women in Science",
    "Surakshit Matritva Aashwasan Yojana",
    "SERB - POWER Research Grants",
    "Biotechnology Career Advancement And Re-orientation (BioCARe) Programme For Women Scientists",
    "India Afghanistan Fellowship",
    "The Inland Waterways Authority of India Internship Scheme",
    "AlCTE - Distinguished Professional Scheme",
    "Central Assistance For One Time Settlement Of Displaced Families From PoK And Chhamb Under Prime Minister's Development Package",
    "Adarsh Gram Yojana",
    "Padho Pardesh",
    "Free Coaching Scheme for SC and OBC Students",
    "E-YUVA Scheme: E-YUVA Centers",
    "Vikaas-Day Care Scheme For Person with Disability Children",
    "AICTE - Distinguished Chair Professor Fellowship",
    "Students Ready",
    "Internship Programme By The Ministry Of External Affairs",
    "INSPIRE Awards – MANAK (Million Minds Augmenting National Aspirations and Knowledge)",
    "E-YUVA Scheme: BIRAC’s E-YUVA Fellows (for under graduate students)",
    "National Solar Science Fellowship Programme",
    "Post-Matric Scholarship for SC students",
    "Welfare Measures for Children of Labourers",
    "AFFDF-Financial Assistance For Treatment Of Serious Diseases To Non Pensioner Ex-Servicemen (All Ranks)/Widows",
    "Pre Matric Scholarship For Scheduled Tribe Students",
    "Babu Jagjivan Ram Chhatrawas Yojna",
    "SERB Science and Technology Award for Research",
    "Design Scheme Under MSME Innovative Scheme",
    "Special Credit Linked Capital Subsidy Scheme (SCLCSS) for Scheduled Caste/Scheduled Tribe",
    "SAHAKAR MITRA: NCDC’s Scheme on Internship Programme",
    "AICTE-Technical Book Writing & Translation Scheme",
    "Collaborative Research Scheme (CRS)",
    "National Savings Certificates (VIII-Issue) Scheme",
    "PM – Surya Ghar: Muft Bijli Yojana",
    "National Startup Awards",
    "Supporting Community Radio Movement in India",
    "Merit Cum Means Based Scholarship For Students Belonging To The Minority Communities",
    "National Centre for Earth Science Studies Internship Scheme",
    "Swachh Bharat Yojana – Grameen Phase II"
  ];

  String? selectedForm;

  Future<bool> _onWillPop() async {
    Navigator.pushNamed(context, '/home');
    return false;
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: _onWillPop,
      child: Scaffold(
        backgroundColor: Colors.white,
        appBar: AppBar(
          title: const Text(
            "Select Form",
            style: TextStyle(color: Colors.white),
          ),
          backgroundColor: Colors.teal,
          iconTheme: const IconThemeData(color: Colors.white),
        ),
        body: LayoutBuilder(
          builder: (context, constraints) {
            return SingleChildScrollView(
              child: ConstrainedBox(
                constraints: BoxConstraints(
                  minHeight: constraints.maxHeight,
                ),
                child: Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      const Text(
                        "Select a Scheme to Proceed:",
                        style: TextStyle(
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                          color: Colors.black87,
                        ),
                      ),
                      const SizedBox(height: 16),
                     DropdownSearch<String>(
  items: formNames,
  dropdownDecoratorProps: DropDownDecoratorProps(
    dropdownSearchDecoration: InputDecoration(
      labelText: "Choose a Scheme",
      labelStyle: TextStyle(
        color: Colors.blueGrey[700],
        fontWeight: FontWeight.w600,
      ),
      border: OutlineInputBorder(
        borderRadius: BorderRadius.circular(15),
        borderSide: BorderSide(
          color: Colors.blueGrey[300]!,
          width: 1.5,
        ),
      ),
      enabledBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(15),
        borderSide: BorderSide(
          color: Colors.blueGrey[300]!,
          width: 1.5,
        ),
      ),
      focusedBorder: OutlineInputBorder(
        borderRadius: BorderRadius.circular(15),
        borderSide: BorderSide(
          color: Colors.teal,
          width: 2,
        ),
      ),
      contentPadding: const EdgeInsets.symmetric(
        horizontal: 15,
        vertical: 18,
      ),
    ),
  ),
  popupProps: PopupProps.menu(
    showSearchBox: true,
    fit: FlexFit.loose,
    
    constraints: BoxConstraints(maxHeight: 400),
    searchFieldProps: TextFieldProps(
      cursorColor: Colors.teal,
      decoration: InputDecoration(
        hintText: "Search forms...",
        hintStyle: TextStyle(color: Colors.blueGrey[400]),
        filled: true,
        fillColor: Colors.blueGrey[50],
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(15),
          borderSide: BorderSide.none,
        ),
        contentPadding: const EdgeInsets.symmetric(
          horizontal: 15,
          vertical: 15,
        ),
        prefixIcon: Icon(
          Icons.search,
          color: Colors.blueGrey[600],
        ),
      ),
    ),
    menuProps: MenuProps(
      borderRadius: BorderRadius.circular(15),
      elevation: 4,
      backgroundColor: Colors.white,
      shadowColor: Colors.black.withOpacity(0.1),
    ),
  ),
  onChanged: (value) {
    setState(() {
      selectedForm = value;
    });
  },
  selectedItem: selectedForm,
),

                      const SizedBox(height: 24),
                      ElevatedButton(
                        onPressed: () async {
                          if (selectedForm != null) {
                            SharedPreferences prefs =
                                await SharedPreferences.getInstance();
                            prefs.setString('selected_form', selectedForm!);
                            
                            Navigator.pushNamed(
                              context,
                              '/camera',
                              arguments: {
                                'selectedForm': selectedForm,
                              },
                            );
                          } else {
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(
                                  content: Text("Please select a form")),
                            );
                          }
                        },
                        style: ElevatedButton.styleFrom(
                          foregroundColor: Colors.white,
                          backgroundColor: Colors.teal,
                          padding: const EdgeInsets.symmetric(vertical: 16),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                          elevation: 5,
                        ),
                        child: const Text(
                          "Proceed",
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}
